name: Github demo
on:
  push:
    branches: main
    paths-ignore: [.github/**]
  pull_request:
    branches: main
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "test ${{ github.event_name}}" /n \
        shell: bash
        


